### ISSUE TITLE
Set up environment for deployment

### ISSUE THREAD

**Issue by satoryu** [satoryu/StayMetalCamera#3]
I wanna try to assemble only Azure resources for this environment. 

First,  investigate Blob and its web container. 
Second, compares other solutions, netlify and github pages. 

## TODO

- [x] Purchase Domain staymetal.fun
- [x] DNS Zone
- [x] Blob Storage for Static Web Contents
- [x] CDN for the static web blob storage
- [x] Add CNAME to Azure DNS Zone
- [x] Configure Custom Domain for CDN endpoint
- [x] SSL: CDN Endpoint supports SSL certification management
- [x] Deploy

## References

* [Tutorial - Add a custom domain to your Azure CDN endpoint | Microsoft Docs](https://docs.microsoft.com/en-us/azure/cdn/cdn-map-content-to-custom-domain)
* [チュートリアル - Web アプリのカスタム Azure DNS レコードの作成 | Microsoft Docs](https://docs.microsoft.com/ja-jp/azure/dns/dns-web-sites-custom-domain)
* [Azure DNS編～新ポータルでDNSを移管する～ – ナレコムAzureレシピ](https://azure-recipe.kc-cloud.jp/2016/04/azure-dns-02/)
* [Azure Storage で静的 Web サイトをホストする | Microsoft Docs](https://docs.microsoft.com/ja-jp/azure/storage/blobs/storage-blob-static-website-how-to?tabs=azure-cli)
* [静的な Web サイトを Azure CDN と統合する - Azure Storage | Microsoft Docs](https://docs.microsoft.com/ja-jp/azure/storage/blobs/static-website-content-delivery-network)
* [静的な Web サイトを Azure CDN と統合する - Azure Storage | Microsoft Docs](https://docs.microsoft.com/ja-jp/azure/storage/blobs/static-website-content-delivery-network#enable-azure-cdn-for-your-static-website)
* [Pricing - Content Delivery Network (CDN) | Microsoft Azure](https://azure.microsoft.com/en-us/pricing/details/cdn/)
